inherit_gem:
  rubocop-ruby1_9: rubocop.yml

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120
